version: "3.9"

services:
  ###########################################################
  # AUTH SERVICE
  ###########################################################
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: auth_service
    env_file:
      - auth_service/.env
    ports:
      - "9001:9001"
    depends_on:
      auth_db:
        condition: service_healthy
    networks:
      - pharma_net

  auth_db:
    image: postgres:15
    container_name: auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - pharma_net

  ###########################################################
  # CATALOG SERVICE + REPLICA
  ###########################################################
  catalog_service:
    build:
      context: .
      dockerfile: catalog_service/Dockerfile
    container_name: catalog_service
    env_file:
      - catalog_service/.env
    ports:
      - "9002:9002"
    depends_on:
      catalog_db:
        condition: service_healthy
    networks:
      - pharma_net

  catalog_service_replica:
    build:
      context: .
      dockerfile: catalog_service/Dockerfile
    container_name: catalog_service_replica
    env_file:
      - catalog_service/.env
    networks:
      - pharma_net

  catalog_db:
    image: postgres:15
    container_name: catalog_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_db
    ports:
      - "5434:5432"
    volumes:
      - catalog_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - pharma_net

  ###########################################################
  # ORDERS SERVICE + REPLICA
  ###########################################################
  orders_service:
    build:
      context: .
      dockerfile: orders_service/Dockerfile
    container_name: orders_service
    env_file:
      - orders_service/.env
    ports:
      - "9003:9003"
    environment:
      REDIS_URL: redis://redis:6379/0
      CATALOG_INTERNAL_URL: http://catalog_service:9002
    depends_on:
      orders_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pharma_net

  orders_service_replica:
    build:
      context: .
      dockerfile: orders_service/Dockerfile
    container_name: orders_service_replica
    env_file:
      - orders_service/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      CATALOG_INTERNAL_URL: http://catalog_service:9002
    networks:
      - pharma_net

  orders_db:
    image: postgres:15
    container_name: orders_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders_db
    ports:
      - "5435:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - pharma_net

  ###########################################################
  # INVENTORY SERVICE
  ###########################################################
  inventory_service:
    build:
      context: .
      dockerfile: inventory_service/Dockerfile
    container_name: inventory_service
    env_file:
      - inventory_service/.env
    ports:
      - "9004:9004"
    environment:
      REDIS_URL: redis://redis:6379/0
      CATALOG_INTERNAL_URL: http://catalog_service:9002
    depends_on:
      inventory_db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - pharma_net

  inventory_db:
    image: postgres:15
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5436:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - pharma_net

  ###########################################################
  # REDIS
  ###########################################################
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 5
    networks:
      - pharma_net

  ###########################################################
  # KONG â€” API GATEWAY
  ###########################################################
 
  kong:
    image: kong:3.6
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,jwt,rate-limiting
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    depends_on:
      redis:
        condition: service_healthy
      auth_service:
        condition: service_started
      catalog_service:
        condition: service_started
      orders_service:
        condition: service_started
      inventory_service:
        condition: service_started
    networks:
      - pharma_net
  ###########################################################
  # NGINX LOAD BALANCER
  ###########################################################
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - kong
    networks:
      - pharma_net

###########################################################
# NETWORKS & VOLUMES
###########################################################
networks:
  pharma_net:

volumes:
  auth_db_data:
  catalog_db_data:
  orders_db_data:
  inventory_db_data:
