global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "auth"
    static_configs:
      - targets: ["auth_service:9001"]

  - job_name: "catalog"
    static_configs:
      - targets: ["catalog_service:9002", "catalog_service_replica:9002"]

  - job_name: "orders"
    static_configs:
      - targets: ["orders_service:9003", "orders_service_replica:9003"]

  - job_name: "inventory"
    static_configs:
      - targets: ["inventory_service:9004"]

  - job_name: "kong"
    static_configs:
      - targets: ["kong:8001"]
